name: Semgrep Scan
on: [push, pull_request, workflow_dispatch]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: returntocorp/semgrep-action@v1
        with:
          # Usa una ruta relativa al repo (montado en el contenedor)
          config: rules/sql-injection.yml
